###### <img src = 'images/sklearn-workflow-title.png'>

<img src = 'images/sk-learn_agenda.png'>

<img src = 'images/sklearn-intro-jupyter-notebook-header.png'>

## 0. An end-to-end Scikit-Learn workflow

In [2]:
# 1. Get the data ready 

import pandas as pd

heart_disease = pd.read_csv("./../data/heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
#create x (features matrix) - input
x = heart_disease.drop('target',axis=1)

# create y (labels) - output
y = heart_disease['target']

In [4]:
# 2. choosing the right right model and the hyper parameter problem

# this is classification problem and we will use Random forest 
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()

# we will keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [5]:
# 3. fit the model to the training data

from sklearn.model_selection import train_test_split

# split the data
# 80% training data and 20% for testing
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [6]:
# training the model
clf.fit(x_train,y_train);

In [7]:
# making pridiction 
y_preds = clf.predict(x_test)
y_preds

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0])

In [8]:
y_test

187    0
6      1
33     1
21     1
128    1
      ..
12     1
176    0
115    1
104    1
260    0
Name: target, Length: 61, dtype: int64

In [9]:
# 4. evaluting the model on the training data and test data

#checking on the training data; 
clf.score(x_train,y_train)
# so it comes 100% of the data it has already seen this data

1.0

In [10]:
#checking it with test data to get the actual score
clf.score(x_test,y_test)

0.8852459016393442

In [11]:
# these are some additional matrics to look at other than just the above score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.88      0.85      0.87        27
           1       0.89      0.91      0.90        34

    accuracy                           0.89        61
   macro avg       0.89      0.88      0.88        61
weighted avg       0.89      0.89      0.88        61



In [12]:
confusion_matrix(y_test,y_preds)

array([[23,  4],
       [ 3, 31]])

In [13]:
accuracy_score(y_test,y_preds)

0.8852459016393442

In [14]:
# 5. improve a model
# try different amount of n_estimators 
# how many estimators are best for our model
import numpy as np
np.random.seed(42)

for i in range(10,100,10):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(x_train,y_train)
    print(f"Model accuracy on test set: {clf.score(x_test,y_test) * 100:0.2f}%")
    print(" ")


Trying model with 10 estimators...
Model accuracy on test set: 85.25%
 
Trying model with 20 estimators...
Model accuracy on test set: 88.52%
 
Trying model with 30 estimators...
Model accuracy on test set: 90.16%
 
Trying model with 40 estimators...
Model accuracy on test set: 90.16%
 
Trying model with 50 estimators...
Model accuracy on test set: 86.89%
 
Trying model with 60 estimators...
Model accuracy on test set: 88.52%
 
Trying model with 70 estimators...
Model accuracy on test set: 88.52%
 
Trying model with 80 estimators...
Model accuracy on test set: 88.52%
 
Trying model with 90 estimators...
Model accuracy on test set: 86.89%
 


In [15]:
# 6. save a model and load it
import pickle

pickle.dump(clf,open("random_forest_model_1.pkl","wb"))

In [16]:
# loading a saved model
loaded_model = pickle.load(open("random_forest_model_1.pkl","rb"))
loaded_model.score(x_test,y_test)

# the accuracy matches with the last one from the loop

0.8688524590163934

In [17]:
# standard imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## 1. Getting the data ready to be used with ML

Three steps process 
 1. Split the data into features and labels(usually x and y)
 2. Filling (also called imputing) or disregarding missing values
 3. Converting non-numerical values to numerical values ( also called feature encoding)

In [18]:
heart_disease = pd.read_csv("./../data/heart-disease.csv")

In [19]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [20]:
# this is the feature dataframe 
x = heart_disease.drop("target",axis=1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [21]:
# the target dataframe

y = heart_disease['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [22]:
# spliting the data into training and test sets. 
from sklearn.model_selection import train_test_split

# 80% is the training and 20% is test
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [23]:
x_train.shape, x_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [24]:
x.shape

(303, 13)

In [25]:
len(heart_disease)

303

### Data Preparation 
* Clean The Data - Avoid, Garbage and any missing values(imputation) 
* Transform The Data - Everything in same unit, text values to numerial values(feature encoding)
* Reducing Data - Training a huge data involves cost - so we can't train everything, sometime we have to reduce the size of the data that we want to train

### 1.1 Making sure everything is numerical  

In [26]:
car_sales = pd.read_csv('./../data/car-sales-extended.csv')
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [27]:
len(car_sales)

1000

In [28]:
car_sales.dtypes

# so we will have encode the 'Make' and 'Colour' coloum to numerical.

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [29]:
# Let's try building the model without encoding

In [30]:
x = car_sales.drop("Price",axis=1)
x.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [31]:
y = car_sales['Price']

In [32]:
x.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [33]:
y.head()

0    15323
1    19943
2    28343
3    13434
4    14043
Name: Price, dtype: int64

In [34]:
# spliting into train and test sets
from sklearn.model_selection import train_test_split 

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [35]:
x_train.shape, x_test.shape,y_train.shape,y_test.shape

((800, 4), (200, 4), (800,), (200,))

In [36]:
# build machine learning model 
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

# this gives an value error, it can't deal with string. 

ValueError: could not convert string to float: 'Toyota'

In [37]:
x.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

#### Feature Encoding - Car Sales - Text to Numerial Values

In [38]:
# trun the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# defind the string columns 
# notice - door is a Categorical feature 
categorial_features = ['Make','Colour','Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorial_features)],
                               remainder="passthrough")
# finally transform 
transformed_x = transformer.fit_transform(x)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [39]:
pd.DataFrame(transformed_x).head()

0    1    2    3    4    5    6    7    8    9    10   11        12
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0

In [40]:
x.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

### One Hot Encoding 

<img src = "images/one-hot-encoding.png">

In [41]:
len(x["Make"].unique()), len(x["Colour"].unique()),len(x["Doors"].unique())

(4, 5, 3)

In [42]:
# one more way of doing it - using Pandas

dummies = pd.get_dummies(car_sales[["Make",'Colour','Doors']])
dummies
# didn't work on the Doors feature 

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [43]:
# Let's refit the model

np.random.seed(42)
x_train,x_test,y_train,y_test = train_test_split(transformed_x,y,test_size=0.2)

# model alreay created above - RandomForestRegressor 
model.fit(x_train,y_train)
model.score(x_test,y_test)

# it works 

0.3235867221569877

#### 1.2 Handling missing values
1. Fill them with some value(imputation). 
2. Remove the samples with missing data altogether. 

In [44]:
missing_car_sales = pd.read_csv('./../data/car-sales-extended-missing-data.csv')
missing_car_sales.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [45]:
# calculate the total missing values in each value 
missing_car_sales.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [46]:
# create x and y

x = missing_car_sales.drop('Price',axis=1)
y = missing_car_sales['Price']

In [47]:
# converting the data to numbers 

from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer

categorial_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()

transformer = ColumnTransformer([('one_hot',
                                 one_hot,
                                 categorial_features)],
                               remainder='passthrough')

transformed_x1 = transformer.fit_transform(missing_car_sales)
trans_missing_car = pd.DataFrame(transformed_x1)

In [48]:
trans_missing_car.head()

# what the fuck is this output 

# check the previous note - the new version of the sklearn doesn't give error when the
# input contains NaNs

# however I think the delow out is anyway not useable 

0
0    (0, 1)\t1.0\n  (0, 9)\t1.0\n  (0, 12)\t1.0\n...
1    (0, 0)\t1.0\n  (0, 6)\t1.0\n  (0, 13)\t1.0\n...
2    (0, 1)\t1.0\n  (0, 9)\t1.0\n  (0, 12)\t1.0\n...
3    (0, 3)\t1.0\n  (0, 9)\t1.0\n  (0, 12)\t1.0\n...
4    (0, 2)\t1.0\n  (0, 6)\t1.0\n  (0, 11)\t1.0\n...

#### Option-1: Fill missing data with Pandas 

In [49]:
# filling the 'Make'

missing_car_sales['Make'].fillna("Missing",inplace=True)

# fill the colour column 
missing_car_sales['Colour'].fillna("Missing",inplace=True)

#fill the Odometer 
missing_car_sales['Odometer (KM)'].fillna(missing_car_sales['Odometer (KM)'].mean(),inplace=True)

# fill the doors coloumn
missing_car_sales["Doors"].fillna(4,inplace=True)

In [50]:
missing_car_sales.isna().sum()
# except price, because this is what we want to predict 
# drop these 50 rows

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [51]:
# we remove the missing label (target variable)

missing_car_sales.dropna(inplace=True)

In [52]:
missing_car_sales.isna().sum()
# no missing values now

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [53]:
len(missing_car_sales)
# lost 50 rows

950

In [54]:
# now doing the feature encoding again

x = missing_car_sales.drop('Price',axis=1)
y = missing_car_sales['Price']

In [55]:
# converting the data to numbers 

from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer

categorial_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()

transformer = ColumnTransformer([('one_hot',
                                 one_hot,
                                 categorial_features)],
                               remainder='passthrough')

transformed_x1 = transformer.fit_transform(missing_car_sales)
pd.DataFrame(transformed_x1)

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   
1    1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   
3    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   
4    0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
945  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
946  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0   
947  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
948  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   
949  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

           14       15  
0     35431.0  15323.0  
1    192714.0  19943.0  
2     84714.0  28343.0  
3    154365.0  13434.0  
4    181577.0  14043.0  
..        ...      ...  
945   35820.0  32042.0  
946  155144.0   5716.0  
947   66604.0  31570.0  
948  215883.0   4001.0  
949  248360.0  12732.0  

[950 rows x 16 columns]

#### Option-2: Fill missing values with Sci-kit Learn

In [56]:
missing_car_sales = pd.read_csv("./../data/car-sales-extended-missing-data.csv")
missing_car_sales

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [57]:
missing_car_sales.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [58]:
# 1. Get rid of rows without price valuess

missing_car_sales.dropna(subset=['Price'],inplace=True)
missing_car_sales.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [59]:
# split into x & y 

x = missing_car_sales.drop('Price',axis=1)
y = missing_car_sales['Price']

x.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [60]:
# fill missing values with Sci-kit learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorial values with 'Missing' and numerial values with Mean
cat_imputer = SimpleImputer(strategy = 'constant',fill_value='Missing')
door_imputer = SimpleImputer(strategy='constant',fill_value=4)
num_imputer = SimpleImputer(strategy='mean')


# define columns

cat_features = ['Make','Colour']
door_feature = ['Doors']
num_features = ['Odometer (KM)']

# create an imputer ( somthing that fills missing data)

imputer = ColumnTransformer([
    ('cat_imputer',cat_imputer,cat_features),
    ('door_imputer',door_imputer,door_feature),
    ('num_imputer',num_imputer,num_features)
])

# transform the data
filled_x = imputer.fit_transform(x)
filled_x

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [61]:
filled_car_sales = pd.DataFrame(filled_x,columns=['Make','Colour','Doors','Odometer (KM)'])


In [62]:
# no missing values

filled_car_sales.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [63]:
# converting the data to numbers 

from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer

categorial_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()

transformer = ColumnTransformer([('one_hot',
                                 one_hot,
                                 categorial_features)],
                               remainder='passthrough')

transformed_x1 = transformer.fit_transform(filled_car_sales)
transformed_x1

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [64]:
# now we have got our data as number with no missing value

# let's fit a model

np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

x_train, x_test, y_train,y_test = train_test_split(transformed_x1,
                                                  y,
                                                  test_size=0.2)

model = RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.2221112515179916

In [65]:
len(filled_car_sales), len(car_sales)

# less rows - low score - draw back
# earlier we had got ~30% accuracy 

(950, 1000)

## 2. Choosing the right estimator / algorithm for your problem

Some things to note:
    
    * Sklearn refers to machine learning models, algorithms as estimators.
    * Classification Problem - predicting a category (heart disearse or not)
    * Sometimes you'll see `clf` (short for classifier) used as a classification estimator
    * Regresssion Problem - predicting a number(selling price of the car)
    
    
Sklearn cheatsheet - https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

<img src = "images/sklearn-ml-map.png">

### 2.1 Picking a machine learning model for a regression problem

Let's use the California housing Price Dataset - Build into Sklearn package

In [9]:
# Get California housing dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [10]:
housing_df = pd.DataFrame(housing["data"],columns=housing['feature_names'])
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [11]:
housing_df['target'] = housing['target']
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

#### Experimentation-01 RidgeRegression

In [69]:
# sklearn cheatsheet- "few feature should be important"??? - RidgeRegression

# experimentation-01

# Import algorithm/estimator 
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split

# Setup random seed
np.random.seed(42)

# Create the data
x = housing_df.drop('target',axis=1) # features
y = housing_df['target'] # meadin house price in $100,000s

# Split the data into train and test sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Instantiate and fit the model (on the training set)

model = Ridge()
model.fit(x_train,y_train)
model.score(x_test,y_test)
# returns the coefficient of determinaiton - how strong liner relationship is
# between two variables - R-square

0.5758549611440125

#### Experimentation-02 SVM - SVR - Linear - Don't Run

In [70]:
'''
# Experimentation-02 - SVR - linear

# Import algorithm/estimator 
from sklearn import svm

# Setup random seed
np.random.seed(42)

# Create the data
x = housing_df.drop('target',axis=1) # features
y = housing_df['target'] # meadin house price in $100,000s

# Split the data into train and test sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Instantiate and fit the model (on the training set)

model = svm.SVR(kernel='linear')
model.fit(x_train,y_train)
model.score(x_test,y_test)
# returns the coefficient of determinaiton - how strong liner relationship is
# between two variables - R-square
''';

#### Experimentation-03 SVM - SVR - rbf - - Don't Run

In [71]:
'''
# Experimentation-02 - SVR - linear

# Import algorithm/estimator 
from sklearn import svm

# Setup random seed
np.random.seed(42)

# Create the data
x = housing_df.drop('target',axis=1) # features
y = housing_df['target'] # meadin house price in $100,000s

# Split the data into train and test sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Instantiate and fit the model (on the training set)

model = svm.SVR(kernel='rbf')
model.fit(x_train,y_train)
model.score(x_test,y_test)
# returns the coefficient of determinaiton - how strong liner relationship is
# between two variables - R-square

''';

#### Experimentation-04 Lasso - Don't Run

In [72]:
'''
# import the model
from sklearn import linear_model 
np.random.seed(42)

# prepare the data
x = housing_df.drop('target',axis=1)
y = housing_df['target']

# split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)


# create the model and fit the data
model = linear_model.Lasso(alpha=0.1)
model.fit(x_train,y_train)
model.score(x_test,y_test)''';

#### Experimentation-04 Ensemble Regressions 

An Ensemble is a combination of smaller models to try and make
better predictions than just a single model.

https://scikit-learn.org/stable/modules/ensemble.html


##### RandomForestRegressor 
https://williamkoehrsen.medium.com/random-forest-simple-explanation-377895a60d2d#:~:text=Well%2C%20congratulations%2C%20we%20have%20created,to%20the%20mark%20on%20average.

In [73]:
# import the model

from sklearn.ensemble import RandomForestRegressor 

np.random.seed(42)

# prepare the data
x = housing_df.drop('target',axis=1)
y = housing_df['target']

# split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)


# create the model and fit the data
model = RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

# from 57% to 80% - nice!!!

0.8066196804802649

### 2.2 Picking a machine learning model for a classification model 

##### My practice

In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

np.random.seed(42)

#get the data
from sklearn.datasets import load_iris
data = load_iris()

# prepare the data
x = pd.DataFrame(data.data,columns=data.feature_names)
y = data.target

# split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#import mode
from sklearn import svm

# create and fit model
model = svm.SVC()
model.fit(x_train,y_train)

#Score 
model.score(x_test,y_test)

1.0

In [75]:
## actual demo

heart_disease = pd.read_csv('./../data/heart-disease.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

#### Consulting the map and it says to try `LinearSVC`

In [76]:
# import the LinearSVC classification class

from sklearn.svm import LinearSVC
np.random.seed(42)

# prepare the feature and target 
x = heart_disease.drop('target',axis=1)
y = heart_disease['target']

#split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# instanticiate the LinearSVC
# warning comes - ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
clf = LinearSVC(max_iter=100000)
clf.fit(x_train,y_train)

# Evaluate the LinearSVC
clf.score(x_test,y_test)

/Users/abhinav/opt/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


0.8852459016393442

In [77]:
## Checking the cheatsheet and applied the best method that we could 

# import the RandomForestClassifier classification class

from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)

# prepare the feature and target 
x = heart_disease.drop('target',axis=1)
y = heart_disease['target']

#split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# instanticiate the LinearSVC
# warning comes - ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
clf = RandomForestClassifier()
clf.fit(x_train,y_train)

# Evaluate the LinearSVC
clf.score(x_test,y_test)

0.8524590163934426

### Summary 
- If you have structured or labeled data use ensemble methods. 
- If you have unstructured data use deep learning use deep or transfer learning.

### 3. Making Prediction

#### 3.1 Fitting the model into the model

x - feature, feature variables, data
y - label, target variables

In [78]:

# import the RandomForestClassifier classification class

from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)

# prepare the feature and target 
x = heart_disease.drop('target',axis=1)
y = heart_disease['target']

#split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# instanticiate the LinearSVC
'''
warning comes - ConvergenceWarning: Liblinear failed to converge, 
increase the number of iterations.
'''
clf = RandomForestClassifier()

# fit the model to the data
clf.fit(x_train,y_train)

# Evaluate the LinearSVC
clf.score(x_test,y_test)


0.8524590163934426

In [79]:
x_test.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
249   69    1   2       140   254    0        0      146      0      2.0   
104   50    1   2       129   196    0        1      163      0      0.0   
300   68    1   0       144   193    1        1      141      0      3.4   
193   60    1   0       145   282    0        0      142      1      2.8   
184   50    1   0       150   243    0        0      128      0      2.6   

     slope  ca  thal  
249      1   3     3  
104      2   0     2  
300      1   2     3  
193      1   2     3  
184      1   0     3

In [80]:
y_test.tail()

249    0
104    1
300    0
193    0
184    0
Name: target, dtype: int64

#### 3.2 Making pridiction using a trained ML model(get the output on the data it hasn't seen)

There are 2 ways to make predictions:
1. prdict()
2. pridict_proba()

#### 3.2.1 Making prediction with predict()

In [81]:

# Use a trained model to make pridictions 

clf.predict(np.array([1,2,3,4,5,6])) # this doesn't work

/Users/abhinav/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 3. 4. 5. 6.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [82]:
clf.predict(x_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [83]:
np.array(y_test)
# y_test is also refers to as the `Grand truth`

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [84]:
x_test.shape

(61, 13)

In [85]:
# Compare prediction to truth labels to evaluate the model

y_preds = clf.predict(x_test)
np.mean(y_preds == y_test) 
# this outputs the accuracy score of the model # clf.score(x_test,y_test)

0.8524590163934426

In [86]:
from sklearn.metrics import accuracy_score
accuracy_score(y_preds,y_test)

0.8524590163934426

##### 3.2.2 Make prediction with predict_proba()

In [87]:
# probability estimates - Probability of a classification label
# gives probability estimate of each output
# puts a number on how much sure the model is on its output 

'''
index0 - 89% sure the output is 0
index1 - 51% sure the output is 1
index2 - 57% sure the output is 1
index3 - 84% sure the output is 0
index4 - 82% sure the output is 1
'''

clf.predict_proba(x_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [88]:
clf.predict(x_test[:5])

array([0, 1, 1, 0, 1])

`predict()` can also be used for regression models

In [89]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [90]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# set the random seed
np.random.seed(42)

# prepare the data
x = housing_df.drop('target',axis=1)
y = housing_df['target']

#split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# instantiate the algo
model = RandomForestRegressor()
#fit the model
model.fit(x_train,y_train)
#evaluation the model
model.score(x_test,y_test)

0.8066196804802649

In [91]:
#making prediction

y_preds = model.predict(x_test)
y_preds[:10]

# the prediction must be in the same scale /format

array([0.49384  , 0.75494  , 4.9285964, 2.54029  , 2.33176  , 1.6549701,
       2.34323  , 1.66182  , 2.47489  , 4.8344779])

In [92]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

In [93]:
len(y_preds), len(y_test)

(4128, 4128)

In [94]:
# look out for regression evaluation matrices 

# mean absolute error 

from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_preds)


### On average, each one of our models predictions is 0.32 different 
### to the actual test value.

0.3265721842781009

In [95]:
# combine together 

y_preds = model.predict(x)
housing_df['preds'] = y_preds
housing_df.head(10)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
5  4.0368      52.0  4.761658   1.103627       413.0  2.139896     37.85   
6  3.6591      52.0  4.931907   0.951362      1094.0  2.128405     37.84   
7  3.1200      52.0  4.797527   1.061824      1157.0  1.788253     37.84   
8  2.0804      42.0  4.294118   1.117647      1206.0  2.026891     37.84   
9  3.6912      52.0  4.970588   0.990196      1551.0  2.172269     37.84   

   Longitude  target     preds  
0    -122.23   4.526  4.260153  
1    -122.22   3.585  3.902470  
2    -122.24   3.521  3.826621  
3    -122.25   3.413  3.608191  
4    -122.25   3.422  2.931000  
5    -122.25   2.697  2.640190  
6    -122.25   2.992  2.356450  
7    -122.25   2.414  2.442430  
8    -122.26   2.267  2.048460  
9    -122.25   2.611  2.652650

## 4.0 Evaluating a machine learning model


Three inbuilt to evaluate Scikit-Learn models/estimators
1. Estimator's built-on `score()` method
2. The `scoring` parameters
3. Problem-specific metric function


You can read more about these here: https://scikit-learn.org/stable/modules/model_evaluation.html

### 4.1 Evaluating the model with the `score` method

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# fix the random seed
np.random.seed(42)

heart_disease = pd.read_csv('./../data/heart-disease.csv')

# create x y
x = heart_disease.drop('target',axis=1)
y = heart_disease['target']

# create split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#Create classifier model instance
clf = RandomForestClassifier()

# fit the classifier training data
clf.fit(x_train,y_train)

# evaluate
clf.score(x_test,y_test)

0.8524590163934426

Let's use the `score()` method on the regression problem...

In [7]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [6]:
new_housing = housing_df.drop('preds',axis=1)
x = new_housing.drop('target',axis=1)
y = new_housing['target']

KeyError: "['preds'] not found in axis"

In [ ]:
x.head()

In [ ]:
y.head()

In [ ]:
# import
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split


# fix the seed
np.random.seed(42)

# split data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#initialise the Regressor 
model = RandomForestRegressor(n_estimators=100)

# fit the model
model.fit(x_train,y_train)

#evaluate 
model.score(x_test,y_test)

# below of the R-squared values 

### 4.2: The `scoring` parameters - `Cross Validation`

In [ ]:
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# fix the random seed
np.random.seed(42)


# create x y
x = heart_disease.drop('target',axis=1)
y = heart_disease['target']

# create split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#Create classifier model instance
clf = RandomForestClassifier()

# fit the classifier training data
clf.fit(x_train,y_train);

In [ ]:
clf.score(x_test,y_test)

In [ ]:
#Takes the classifer, and the entire features and target variable
# not the test, train split
cross_val_score(clf,x,y,cv=5)

# this returns an array

<img src = 'images/sklearn-cross-validation.png'>

Model is trained on 5 different versions of training data, and evaluated on
5 different versions of the test data.

This avoids geting a lucky score on a single test split

5 fold is default and usually good enough.

In [ ]:
np.random.seed(42)

#single training and test split score
clf_single_score = clf.score(x_test,y_test)

#take the mean of 5-fold cross-validation score
clf_cross_val_score = np.mean(cross_val_score(clf,x,y,cv=5))

#compare the two 
clf_single_score, clf_cross_val_score

# cross validation method is used over just the `score()`

In [ ]:
# scoring parameter set ot None by default 
cross_val_score(clf,x,y,cv=5,scoring=None)

# When the scoring is set to None, the cross_val_score is going to -
# - use the default scoring parameter of classifier = mean accuracy 

#### 4.2.1 Classificaiton model evaluation metrics

1. Accuracy
2. Area under the ROC curve
3. Confusion matrix
4. Classification report

#### 4.2.1.1 Accuracy 

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

np.random.seed(42)

x = heart_disease.drop('target',axis=1)
y = heart_disease['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

clf = RandomForestClassifier(n_estimators=100)

clf.fit(x_train,y_train)

clf.score(x_test,y_test)

In [ ]:
score_corss_val = cross_val_score(clf,x,y,cv=5)
np.mean(score_corss_val)

In [ ]:
print(f"Heart Disease Classifier Cross-Validated Accuracy: {np.mean(score_corss_val)*100:.2f}")


#### 4.2.1.2 Area under the ROC curve

Receiver Operator Characteristics Curve

* Area under the Curve(AUC)
* ROC Curve

ROC curve are a comparision of a model's true positive rate(tpr) versus a models false positive rate(fpr)

* True positive - model predicts 1 when truth is 1
* False positive - model predicts 1 when truth is 0
* True negative - model predicts 0 when truth is 0
* False negative - model preducts 0 when truth is 1

In [ ]:
# split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.metrics import roc_curve

# fit the model
clf.fit(x_train,y_train)
# make prediction with probabilities

# predict with probability
y_probs = clf.predict_proba(x_test)

y_probs[:5]

In [ ]:
y_probs_positive = y_probs[:,1]
y_probs_positive[:10]

In [ ]:
# Caculaute fpr, tpr and thresholds

fpr, tpr, thresholds = roc_curve(y_test,y_probs_positive)

In [ ]:
thresholds

In [ ]:
# create a function for ploting ROC curve

import matplotlib.pyplot as plt

def plot_roc_curve(fpr,tpr):
    """
    Plots a ROC curve give the false positive rate fpr 
    and true positive rate (tpr) of a model
    """
    
    #plot roc curve
    plt.plot(fpr,tpr,color='orange',label='ROC')
    #plot line with no predictive power (baseline)
    #plt.plot([0,1],[0,1],color='darkblue',linestyle='--',label='Guessing')
    # customise the plot
    plt.xlabel('False Positive Rate (fpr)')
    plt.ylabel('True Positive Rate (tpr)')
    plt.title('Receiver Operating Characteristic (ROC) Curve')

plot_roc_curve(fpr,tpr)

In [ ]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,y_probs_positive)

In [ ]:
# plot perfect ROC curve and AUC score

fpr, tpr, thresholds = roc_curve(y_test,y_test)
plot_roc_curve(fpr,tpr)


In [ ]:
#perfect AUC score
roc_auc_score(y_test,y_test)

Reading Extension: ROC Curve + AUC
When you first encounter them, ROC Curve and AUC (area under curve) metrics can be a little confusing. But not to worry, with a little practice, they'll start to make sense.

In a nutshell, what you should remember is:

* ROC curves and AUC metrics are evaluation metrics for binary classification models (a model which predicts one thing or another, such as heart disease or not).

* The ROC curve compares the true positive rate (tpr) versus the false positive rate (fpr) at different classification thresholds.

* The AUC metric tells you how well your model is at choosing between classes (for example, how well it is at deciding whether someone has heart disease or not). A perfect model will get an AUC score of 1.

For more information on these metrics, bookmark the following resources and refer to them when you need:

* ROC and AUC, Clearly Explained! by StatQuest - https://www.youtube.com/watch?v=4jRBRDbJemM&ab_channel=StatQuestwithJoshStarmer

* ROC documentation in Scikit-Learn (contains code examples) - https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html

* How the ROC curve and AUC are calculated by Google's Machine Learning team - https://developers.google.com/machine-learning/crash-course/classification/roc-and-auc

#### 4.2.1.3 Confusion Matrix

A confusion matrix is a quick way to compare the labels a model predicts and the actual labels it was supposed to predict.
In essence, giving you an idea of where the model is getting confused. 

<img src='images/sklearn-confusion-matrix-anatomy.png'>

In [ ]:
from sklearn.metrics import confusion_matrix

y_preds = clf.predict(x_test)
confusion_matrix(y_test,y_preds)

In [ ]:
# Visualise confusion matrix with pd.crosstab()

pd.crosstab(y_test,y_preds,rownames=['Actual Labels'],
            colnames=['Preducted Labels'])

In [ ]:
# Make our confusion matrix more visual with Searborn's heatmap()

import seaborn as sns

# Set the font scale
sns.set(font_scale=1.5)

# Create a confusion matrix
conf_mat = confusion_matrix(y_test,y_preds)

# plot it using seaborn
sns.heatmap(conf_mat);

### Creating a confusion matrix using Scikit learn

To use the new methods of creating a confusion matrix with Scikit-learn. You will need
Scikit learn 1.0+

In [ ]:
import sklearn
sklearn.__version__

In [ ]:
clf

In [ ]:
from sklearn.metrics import ConfusionMatrixDisplay

# plot it from the estimators on the entire dataset
ConfusionMatrixDisplay.from_estimator(estimator=clf,X=x,y=y);

In [ ]:
# plot it on the predictions only
ConfusionMatrixDisplay.from_predictions(y_true=y_test,y_pred=y_preds);

#### 4.2.1.4 Classification Report

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_preds))

<img src='images/sklearn-classification-report-anatomy.png'>

In [ ]:
#### How some matrix can be deceptive 

#### Where precision and recall become valuable

# let's say we are given data about 10000 patients 
disease_true = np.zeros(10000)
# only one of the patient has the disease
disease_true[0] = 1 # only one positive case

# but the model that we created predicts every case as 0
disease_preds = np.zeros(10000) 

pd.DataFrame(classification_report(disease_true,disease_preds,output_dict=True))


## so incase of very high Class-Imbalances the accuracy is very misleading 
## - so check for other metrics well - use a wide specturm of metrics  

## 4.2.2 Regression Model Evaluation Metrics

Model evaluation metrics documentation - https://scikit-learn.org/stable/modules/model_evaluation.html#regression-metrics

Agenda
1. R-square or Cofficient of Determination 
2. Mean absolute error (MAE)
3. Mean Squared Error (MSE)

#### 4.2.2.1 R-square or Cofficient of Determination 


In [24]:
# Get California housing dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing;

In [12]:
housing_df = pd.DataFrame(housing["data"],columns=housing['feature_names'])
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [13]:
housing_df['target'] = housing['target']
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [14]:
from sklearn.ensemble import RandomForestRegressor 

np.random.seed(42)

x = housing_df.drop('target',axis=1)
y = housing_df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

model = RandomForestRegressor(n_estimators=100)
model.fit(x_train,y_train)

RandomForestRegressor()

In [15]:
# The following is the R-square metric
model.score(x_test,y_test)

0.8066196804802649

In [17]:
# The R2 score will be zero if the our model predicts all the values equal to 
# the average of Y-test, following is a test for that 

from sklearn.metrics import r2_score

#fill an array with y_test mean
y_test_mean = np.full(len(y_test),y_test.mean())

In [19]:
y_test_mean[:10]

array([2.0550031, 2.0550031, 2.0550031, 2.0550031, 2.0550031, 2.0550031,
       2.0550031, 2.0550031, 2.0550031, 2.0550031])

In [21]:
# This R2 score 
r2_score(y_true=y_test,y_pred=y_test_mean)

# R2 score can also go -ve

0.0

In [22]:
# perfect model
r2_score(y_true=y_test,y_pred=y_test)

1.0

#### 4.2.2.2 Mean absolute error (MAE) 

MAE is the average of the absolute difference between predictions and actual values.

It gives you an idea of how wrong your model predictions are.

In [27]:
from sklearn.metrics import mean_absolute_error

y_preds = model.predict(x_test)

mae = mean_absolute_error(y_true=y_test,y_pred=y_preds)
mae

0.3265721842781009

In [28]:
y_preds

array([0.49384  , 0.75494  , 4.9285964, ..., 4.8363785, 0.71782  ,
       1.67901  ])

In [29]:
y_test

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...   
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: target, Length: 4128, dtype: float64

In [30]:
# confirmation
df = pd.DataFrame(data={'actual values':y_test,
                       "predicted values":y_preds})
df['difference'] = df['predicted values']  - df['actual values']
df.head(10)

actual values  predicted values  difference
20046        0.47700          0.493840    0.016840
3024         0.45800          0.754940    0.296940
15663        5.00001          4.928596   -0.071414
20484        2.18600          2.540290    0.354290
9814         2.78000          2.331760   -0.448240
13311        1.58700          1.654970    0.067970
7113         1.98200          2.343230    0.361230
7668         1.57500          1.661820    0.086820
18246        3.40000          2.474890   -0.925110
5723         4.46600          4.834478    0.368478

In [34]:
# MAE using the differences and formula 
np.abs(df['difference']).mean()

0.32657218427810186

#### 4.2.2.3 Mean Squared Error (MSE)

MAE is the mean of the square of the erros between actual and predicted values

In [38]:
from sklearn.metrics import mean_squared_error

y_preds = model.predict(x_test)
mse = mean_squared_error(y_test,y_preds)
mse

0.2534073069137548

In [39]:
df['sq_diff'] = np.square(df['difference'])
df.head()

actual values  predicted values  difference   sq_diff
20046        0.47700          0.493840    0.016840  0.000284
3024         0.45800          0.754940    0.296940  0.088173
15663        5.00001          4.928596   -0.071414  0.005100
20484        2.18600          2.540290    0.354290  0.125521
9814         2.78000          2.331760   -0.448240  0.200919

In [40]:
# Calculate MSE by hand

squared = np.square(df['difference'])

np.mean(squared)

0.253407306913755

In [42]:
# calculate MSE with large error 

df_large_error = df.copy()
df_large_error.iloc[0]['sq_diff'] = 16

In [43]:
df_large_error

actual values  predicted values  difference    sq_diff
20046        0.47700          0.493840    0.016840  16.000000
3024         0.45800          0.754940    0.296940   0.088173
15663        5.00001          4.928596   -0.071414   0.005100
20484        2.18600          2.540290    0.354290   0.125521
9814         2.78000          2.331760   -0.448240   0.200919
...              ...               ...         ...        ...
15362        2.63300          2.220380   -0.412620   0.170255
16623        2.66800          1.947760   -0.720240   0.518746
18086        5.00001          4.836378   -0.163632   0.026775
2144         0.72300          0.717820   -0.005180   0.000027
3665         1.51500          1.679010    0.164010   0.026899

[4128 rows x 4 columns]

In [45]:
df_large_error['sq_diff'].mean()
# It didn't make that much difference 

0.2572832072079409

In [48]:
# make more large errors 

df_large_error.iloc[1:100] = 20
df_large_error['sq_diff'].mean()

# now we get a large MAE value 

0.7333540351264827

<img src = 'images/regression_metrics.png'>

#### Nice summary - https://www.udemy.com/course/complete-machine-learning-and-data-science-zero-to-mastery/learn/lecture/17690056#overview

### 4.2.3 Finally using the `scoring` Parameter

In [50]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

heart_disease = pd.read_csv('./../data/heart-disease.csv')

x = heart_disease.drop('target',axis=1)
y = heart_disease['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
clf = RandomForestClassifier(n_estimators=100)


In [56]:
np.random.seed(42)

#cross validation accuracy 
cv_acc = cross_val_score(clf,x,y,cv=5,scoring=None)
np.mean(cv_acc)

0.8248087431693989

In [57]:
# Cross validated accuracy 
print(f"The cross validated accuracy is: {np.mean(cv_acc)*100:0.2f}%")

The cross validated accuracy is: 82.48%


In [60]:
np.random.seed(42)
cv_acc = cross_val_score(clf,x,y,cv=5,scoring='accuracy')

# Cross validated accuracy 
print(f"The cross validated accuracy is: {np.mean(cv_acc)*100:0.2f}%")

The cross validated accuracy is: 82.48%


In [63]:
# precision 
np.random.seed(42)

cv_precision = cross_val_score(clf,x,y,cv=5,scoring='precision')
cv_precision

# depending upon the split of the data the model perform differently

array([0.82352941, 0.93548387, 0.84848485, 0.79411765, 0.76315789])

In [65]:
# Cross validated precison 
print(f"The cross validated precisoon is: {np.mean(cv_precision)*100:0.2f}")

The cross validated precisoon is: 83.30


In [66]:
# Recall 
np.random.seed(42)
cv_recall = cross_val_score(clf,x,y,cv=5,scoring='recall')
cv_recall

array([0.84848485, 0.87878788, 0.84848485, 0.81818182, 0.87878788])

In [68]:
# Cross Validated Recall 
print(f"The cross validated recall is: {np.mean(cv_recall)}")

The cross validated recall is: 0.8545454545454545


### `Scoring` parameter for the Regression Metrics

In [70]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

x = housing_df.drop('target',axis=1)
y = housing_df['target']

model = RandomForestRegressor(n_estimators=100)

In [71]:
np.random.seed(42)

cv_r2 = cross_val_score(model,x,y,cv=3,scoring=None) #default is R2
np.mean(cv_r2)

0.6545756342466266

In [72]:
# Cross Validated R2 
print(f"The cross validated R2 is: {np.mean(cv_r2)}")

The cross validated R2 is: 0.6545756342466266


In [83]:
# Mean Absolute Error
np.random.seed(42)
cv_mae = cross_val_score(model,x,y,cv=5,scoring='neg_mean_absolute_error')
cv_mae
#high varience 

array([-0.54255936, -0.40903449, -0.43716367, -0.46911343, -0.47319069])

In [78]:
# Cross Validated MAE 
print(f"The cross validated MAE is: {np.mean(cv_mae)}")

# the lower is the better 

The cross validated MAE is: -0.48487437131782957


In [84]:
# Mean Squared Error
np.random.seed(42)
cv_mse = cross_val_score(model,x,y,cv=5,scoring='neg_mean_squared_error')

# Cross Validated MAE 
print(f"The cross validated MSE is: {np.mean(cv_mse)}")
# the higer is the better 

The cross validated MSE is: -0.43011254261460774


In [85]:
cv_mse
#high varience between diffrent split of the data

array([-0.51906307, -0.34788294, -0.37112854, -0.44980156, -0.4626866 ])

### 4.3 Metric Function 

The 3rd way to evaluate scikit-learn machine learning models/estimators to using the `sklearn.metrics`

In [98]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

np.random.seed(42)
# create x & y
x = heart_disease.drop('target',axis=1)
y = heart_disease['target']

# split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#create model
clf = RandomForestClassifier()

#fit model
clf.fit(x_train,y_train)

y_preds = clf.predict(x_test)

#evaluate model using evaluate funcutions
print("Classification metrics on the test set")
print(f"Accuracy: {accuracy_score(y_test,y_preds)*100:0.2f}%")
print(f"Precision: {precision_score(y_test,y_preds)}")
print(f"Recall: {recall_score(y_test,y_preds)}")
print(f"F1: {f1_score(y_test,y_preds)}")

Classification metrics on the test set
Accuracy: 85.25%
Precision: 0.8484848484848485
Recall: 0.875
F1: 0.8615384615384615


In [101]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
np.random.seed(42)

# create x & y
x = housing_df.drop('target',axis=1)
y = housing_df['target']

# split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#create model
model = RandomForestRegressor()
#fit model
model.fit(x_train,y_train)

y_preds = model.predict(x_test)

#evaluate model using evaluate funcutions
print("Regression metrics on the test set")
print(f"R2: {r2_score(y_test,y_preds)}")
print(f"MAE: {mean_absolute_error(y_test,y_preds)}")
print(f"MSE: {mean_squared_error(y_test,y_preds)}")


Regression metrics on the test set
R2: 0.8066196804802649
MAE: 0.3265721842781009
MSE: 0.2534073069137548
